@1. PresentationLayer_HostAddress = http://localhost:5120
@_1._PresentationLayer_HostAddress = http://localhost:5120

GET {{_1._PresentationLayer_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{1. PresentationLayer_HostAddress}}/api/product

###

POST {{1. PresentationLayer_HostAddress}}/api/product
Content-Type: application/json

{
  //Product
}

###

GET {{1. PresentationLayer_HostAddress}}/api/product

###
